### ISSUE TITLE
invalid load key, 'v'

### ISSUE THREAD

**Issue by crazy-hair** [Krischan74/RTCWHQ#3]
Whenever I try to run convert.cmd, it unloads the PK3s into folders, and then when it tries to run RTCWHQ.py, it comes up with this error:

```
Puny human is instructed to wait until the models are been prepared...
Traceback (most recent call last):
  File "rtcwhq.py", line 179, in <module>
    model.load_state_dict(torch.load(model_path), strict=True)
  File "C:\Users\crazy\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\crazy\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

I've installed all the dependencies, and I'm not too code-savvy, could anyone help me figure this out?

**Comment by dclmetatiger** [comment]
Line 179 loads the model. Either your "torch" dependency is faulty, or the first model. Did you use my included models or a custom one? Default is "models/cartoonpainted_400000.pth"

But to me it looks like there is a problem with the dependency. Try "pip3 list" in a commandline window and check if torch is there and version is at least like in my installation:

C:\Users\Christian>pip3 list
Package        Version
-------------- -----------
altgraph       0.16.1
future         0.17.1
lmdb           0.94
macholib       1.11
numpy          1.16.3
opencv-python  4.1.0.25
pefile         2019.4.18
Pillow         6.0.0
pip            19.1
protobuf       3.7.1
PyInstaller    3.4
PyQt5          5.12.1
PyQt5-sip      4.19.15
pywin32-ctypes 0.2.0
setuptools     40.8.0
six            1.12.0
tensorboardX   1.6
torch          1.0.1
torchvision    0.2.2.post3

**Comment by crazy-hair** [comment]
I'm using the included models

```
Package        Version
-------------- -----------
altgraph       0.16.1
cffi           1.12.3
future         0.17.1
macholib       1.11
numpy          1.16.4
opencv-python  4.1.0.25
packaging      19.0
pefile         2019.4.18
Pillow         6.0.0
pip            19.1.1
pip-review     1.0
pyclipper      1.1.0.post1
pycparser      2.19
PyInstaller    3.4
pyparsing      2.4.0
pywin32-ctypes 0.2.0
setuptools     41.0.1
six            1.12.0
torch          1.1.0
torchvision    0.3.0
wheel          0.33.4
```

**Comment by dclmetatiger** [comment]
Hmm difficult to say. I have uploaded two ZIP files to Mediafire containing my Python37 and RTCWHQ folder. Just overwrite your existing Python installation if you only use it for RTCWHQ currently. The RTCWHQ folder can be anywhere, it is only important that python.exe is reachable from there.

[Python37.zip](http://www.mediafire.com/file/il3h07mmpana2bb/Python37.zip/file) 910MB
[RTCWHQ.zip](http://www.mediafire.com/file/368mwaimrej2ae7/RTCWHQ.zip/file) 241MB

**Comment by crazy-hair** [comment]
The RTCWHQ.zip you attached seems to work, I didn't even need the python zip you attached. Thank you.
